search_rules:
  from-date: 2019-06-16 22:00
  to-date: 2019-06-16 23:59
  pt-rule: '#showdopavao'

search_params:
  results-per-call: 100
  max-results: 100

output_params:
  save_file: True
  filename_prefix: showdopavao_1
  results_per_file: 10000000
